# KubeBao Dynamic Secrets Demo
# This example demonstrates:
# 1. Direct injection of secrets into pods via CSI
# 2. Automatic secret rotation without pod restart
# 3. Syncing CSI secrets to Kubernetes Secrets

---
# ServiceAccount for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: default

---
# SecretProviderClass - defines how to fetch secrets from OpenBao
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kubebao-demo-secrets
  namespace: default
spec:
  provider: kubebao
  parameters:
    # OpenBao role for authentication (must match ServiceAccount)
    roleName: "my-app"
    # OpenBao address (use cluster internal address)
    openbaoAddr: "http://openbao.openbao.svc.cluster.local:8200"
    # List of secrets to fetch
    objects: |
      - objectName: "db-password"
        secretPath: "myapp/database"
        secretKey: "password"
      - objectName: "db-username"
        secretPath: "myapp/database"
        secretKey: "username"
      - objectName: "db-host"
        secretPath: "myapp/database"
        secretKey: "host"
      - objectName: "config.json"
        secretPath: "myapp/config"
  # Optional: Sync CSI secrets to a Kubernetes Secret
  secretObjects:
    - secretName: demo-synced-secret
      type: Opaque
      data:
        - objectName: db-password
          key: password
        - objectName: db-username
          key: username

---
# Demo application that reads secrets from mounted volume
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: demo-app
      containers:
        - name: app
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "=== KubeBao Dynamic Secrets Demo ==="
              echo "Secrets are mounted at /mnt/secrets"
              echo ""
              while true; do
                echo "--- $(date) ---"
                echo "Database Password: $(cat /mnt/secrets/db-password)"
                echo "Database Username: $(cat /mnt/secrets/db-username)"
                echo "Database Host: $(cat /mnt/secrets/db-host)"
                echo ""
                echo "If you change the secret in OpenBao, it will be updated here automatically!"
                echo "Try: bao kv put secret/myapp/database username=newuser password=newpass host=newhost port=5432"
                echo ""
                sleep 30
              done
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "kubebao-demo-secrets"

---
# BaoSecret - Alternative: use operator for sync
# This syncs secrets from OpenBao to Kubernetes Secret
# and automatically updates when secrets change in OpenBao
apiVersion: kubebao.io/v1alpha1
kind: BaoSecret
metadata:
  name: demo-operator-secret
  namespace: default
spec:
  secretPath: "myapp/config"
  target:
    name: demo-operator-synced
    labels:
      app: demo
      managed-by: kubebao
  refreshInterval: "30s"  # Check for updates every 30 seconds
